AddCSLuaFile( "cl_init.lua" )
AddCSLuaFile( "shared.lua" )

include('shared.lua')

ENT.StartHealth = 100

ENT.Models = { "models/Humans/Group01/Female_01.mdl",
"models/Humans/Group01/Female_02.mdl",
"models/Humans/Group01/Female_03.mdl",
"models/Humans/Group01/Female_04.mdl",
"models/Humans/Group01/Female_06.mdl",
"models/Humans/Group01/Female_07.mdl",
"models/Humans/Group02/Female_01.mdl",
"models/Humans/Group02/Female_02.mdl",
"models/Humans/Group02/Female_03.mdl",
"models/Humans/Group02/Female_04.mdl",
"models/Humans/Group02/Female_06.mdl",
"models/Humans/Group02/Female_07.mdl" }

ENT.Pain = { "vo/npc/female01/moan03.wav",
"vo/npc/female01/moan02.wav",
"vo/npc/female01/moan01.wav",
"vo/npc/female01/ow01.wav",
"vo/npc/female01/ow02.wav",
"vo/npc/female01/ohno.wav",
"vo/npc/female01/pain02.wav",
"vo/npc/female01/startle01.wav",
"vo/npc/female01/startle02.wav",
"vo/trainyard/wife_please.wav",
"vo/trainyard/wife_canttake.wav",
"vo/npc/female01/gordead_ans04.wav",
"vo/npc/female01/gordead_ans05.wav",
"vo/npc/female01/gordead_ans06.wav",
"vo/npc/female01/myarm01.wav",
"vo/npc/female01/myarm02.wav",
"vo/npc/female01/hitingut02.wav",
"vo/npc/female01/mygut02.wav",
"vo/npc/female01/myleg01.wav",
"vo/npc/female01/myleg02.wav",
"vo/npc/female01/imhurt01.wav",
"vo/npc/female01/imhurt02.wav" }

ENT.Death = { "vo/canals/arrest_helpme.wav",
"vo/npc/female01/gordead_ans04.wav",
"vo/npc/female01/gordead_ans06.wav",
"vo/npc/female01/help01.wav",
"vo/npc/female01/no01.wav",
"vo/npc/female01/no02.wav",
"ambient/voices/f_scream1.wav",
"vo/coast/odessa/female01/nlo_cubdeath01.wav",
"vo/coast/odessa/female01/nlo_cubdeath02.wav",
"vo/npc/female01/pain01.wav",
"vo/npc/female01/pain02.wav",
"vo/npc/female01/pain03.wav",
"vo/npc/female01/pain04.wav",
"vo/npc/female01/pain05.wav",
"vo/npc/female01/pain06.wav",
"vo/npc/female01/pain07.wav",
"vo/npc/female01/pain08.wav",
"vo/npc/female01/pain09.wav" }

ENT.Scream = { "vo/npc/female01/incoming02.wav",
"vo/canals/female01/stn6_incoming.wav",
"vo/npc/female01/strider_run.wav",
"vo/npc/female01/question01.wav",
"vo/npc/female01/question11.wav",
"vo/npc/female01/behindyou01.wav",
"vo/npc/female01/behindyou02.wav",
"vo/npc/female01/heretheycome01.wav",
"vo/npc/female01/takecover02.wav",
"vo/npc/female01/gethellout.wav",
"vo/npc/female01/watchout.wav",
"vo/npc/female01/letsgo01.wav",
"vo/npc/female01/letsgo02.wav",
"vo/npc/female01/headsup01.wav",
"vo/npc/female01/headsup02.wav",
"vo/npc/female01/overhere01.wav",
"vo/npc/female01/readywhenyouare01.wav",
"vo/npc/female01/readywhenyouare02.wav",
"vo/npc/female01/overthere01.wav",
"vo/npc/female01/overthere02.wav" }