resource.AddFile( "models/blackops/pitfall/platform.dx80.vtx" )
resource.AddFile( "models/blackops/pitfall/platform.dx90.vtx" )
resource.AddFile( "models/blackops/pitfall/platform.mdl" )
resource.AddFile( "models/blackops/pitfall/platform.phy" )
resource.AddFile( "models/blackops/pitfall/platform.sw.vtx" )
resource.AddFile( "models/blackops/pitfall/platform.vvd" )
resource.AddFile( "models/blackops/pitfall/platform.xbox.vtx" )

--[[resource.AddFile( "models/blackops/pitfall/power_box.dx80.vtx" )
resource.AddFile( "models/blackops/pitfall/power_box.dx90.vtx" )
resource.AddFile( "models/blackops/pitfall/power_box.mdl" )
resource.AddFile( "models/blackops/pitfall/power_box.phy" )
resource.AddFile( "models/blackops/pitfall/power_box.sw.vtx" )
resource.AddFile( "models/blackops/pitfall/power_box.vvd" )
resource.AddFile( "models/blackops/pitfall/power_box.xbox.vtx" )]]

//resource.AddFile("materials/models/blackops/pitfall/black.vmt")
//resource.AddFile("materials/models/blackops/pitfall/black.vmt")
resource.AddFile("materials/models/blackops/pitfall/platform_sheet.vmt")
resource.AddFile("materials/models/blackops/pitfall/platform_sheet.vmt")
resource.AddFile("materials/models/blackops/pitfall/platform_sheet_normal.vtf")
//resource.AddFile("materials/models/blackops/pitfall/white.vmt")
//resource.AddFile("materials/models/blackops/pitfall/white.vmt")