ENT.Base = "base_anim"
ENT.Type = "anim"
ENT.Category 			= "cratewars"
ENT.PrintName			= "cw_bomb"
ENT.Author			= "Paul Sweeney and Doug Huck"
ENT.Contact			= ""
ENT.Purpose			= "cw_bomb"
ENT.Instructions		= ""
ENT.Spawnable			= true
ENT.AdminSpawnable		= true
