ENT.Type 			= "anim"
ENT.Base 			= "base_anim"
ENT.PrintName		= "Pressure Plate"
ENT.Author			= "Levybreak"
ENT.Contact 		= "Facepunch"
ENT.Purpose			= ""
ENT.Instructions	= "Don't stand on it." 