resource.AddFile("models/weapons/v_oddball.mdl")
resource.AddFile("models/weapons/w_oddball.mdl")
resource.AddFile("models/oddball/oddball.mdl")

resource.AddFile("materials/gmod/scope.vmt")
resource.AddFile("materials/gmod/scope.vtf")
resource.AddFile("materials/gmod/scope-refract.vmt")
resource.AddFile("materials/gmod/scope-refract.vtf")

resource.AddFile("materials/models/oddball/oddball.vmt")
resource.AddFile("materials/models/oddball/oddball.vtf")

resource.AddFile("materials/oddball/blue_arrow.vmt")
resource.AddFile("materials/oddball/blue_arrow.vtf")
resource.AddFile("materials/oddball/red_arrow.vmt")
resource.AddFile("materials/oddball/red_arrow.vtf")
resource.AddFile("materials/oddball/grey_arrow.vmt")
resource.AddFile("materials/oddball/grey_arrow.vtf")
resource.AddFile("materials/oddball/team_arrow.vmt")
resource.AddFile("materials/oddball/team_arrow.vtf")
resource.AddFile("materials/oddball/radar.vmt")
resource.AddFile("materials/oddball/radar.vtf")

resource.AddFile("sound/oddball/captured.wav")
resource.AddFile("sound/oddball/dropped.wav")
resource.AddFile("sound/oddball/bluewins.wav")
resource.AddFile("sound/oddball/redwins.wav")